// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKXzPxTiKlk1HEWZwa8VYCrLVvL37WJo',
    appId: '1:94295445922:web:4fa84b8493c195322aa2fb',
    messagingSenderId: '94295445922',
    projectId: 'movie-box-7c4f1',
    authDomain: 'movie-box-7c4f1.firebaseapp.com',
    storageBucket: 'movie-box-7c4f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdK7cscyFq7RLLL3c_d68INBYOULK3ij0',
    appId: '1:94295445922:android:9e6bc922a7bc4a882aa2fb',
    messagingSenderId: '94295445922',
    projectId: 'movie-box-7c4f1',
    storageBucket: 'movie-box-7c4f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5qlQI3KWboEw5ealpriS0ARuj98MpK8',
    appId: '1:94295445922:ios:db4ac4bae9affb532aa2fb',
    messagingSenderId: '94295445922',
    projectId: 'movie-box-7c4f1',
    storageBucket: 'movie-box-7c4f1.appspot.com',
    iosBundleId: 'com.example.classic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5qlQI3KWboEw5ealpriS0ARuj98MpK8',
    appId: '1:94295445922:ios:d1c3f74f7581c8942aa2fb',
    messagingSenderId: '94295445922',
    projectId: 'movie-box-7c4f1',
    storageBucket: 'movie-box-7c4f1.appspot.com',
    iosBundleId: 'com.example.classic.RunnerTests',
  );
}
